name: Test and Deploy

on:
  pull_request:
    branches: [main]

# Ensure only one deployment runs at a time
concurrency:
  group: deploy-main
  cancel-in-progress: true

# Required for OIDC token generation
permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          CI: true
        timeout-minutes: 5

  diff:
    needs: test
    runs-on: ubuntu-latest
    # Only run diff on PRs
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: us-east-1
          role-session-name: GitHubActions-CDKDiff

      - name: Show infrastructure changes
        run: |
          echo "🔍 Infrastructure changes in this PR:"
          npx cdk diff --require-approval never || true